#!/usr/bin/env bash
# Run this to generate the C# bindings. Uncomment the lines below to
# recreate the API file (GtkSheetSharp-api.xml) from the C sources.

outdir=Generated
sourcever=4.3.5
url=https://github.com/fpaquet/gtksheet/archive/V$sourcever.tar.gz
sourcedir=gtksheet-$sourcever
localfile=$sourcedir.tar.gz
tempapi=GtkSheetSharp-api.xml
api=$outdir/$tempapi
metadata=GtkSheetSharp.metadata
sourcefile=GtkSheetSharp.source

#wget $url -O $localfile
#tar xf $localfile
#gapi3-parser $sourcefile || exit
#rm $localfile
#rm -rf $sourcedir

if [ -d $outdir ];
then
    rm -rf $outdir
fi

mkdir $outdir
cp $tempapi $api

gapi3-fixup --api=$api --metadata=$metadata || exit
gapi3-codegen --outdir=$outdir `pkg-config --cflags gtk-sharp-3.0` --include=../GtkSharp/Source/Libs/CairoSharp/Generated/CairoSharp-api.xml --generate $api
